brand:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Ploom
code_product:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: BD272
code_sku:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 20BD272250
country:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: IT
description:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: PLOOM DEVICE BLACK
description_configurable_ecom:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Ploom Device
description_simple_ecom:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Ploom Device
harmonization_status:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: VALID
id_legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '11'
id_product_configurable:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '83'
is_configurable:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Y
legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: TME
producer_code:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '0000120754'
product_category:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Device
product_color:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ''
rep_code:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: R08
sale_type_code:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: E
sector_code:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: F1
