attachment_url:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '''https://productreviews-attachments.trustpilot.com/5f5f56893efb540001731515_original.png'''
id_attribute:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: attributes.default.quality
attribute_name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Quality
brand:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Acme
consumer_email:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '''customer@somewhere.com'''
consumer_name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Customer
content:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: This product was nice, but slightly too expensive.
country:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: DES_MKT
created_at:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '''2021-07-19 12:38:29'''
event_id:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 54bffd360000640002975392
harmonization_status:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '''VALID'''
has_moderation_history:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 'true'
id:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '6'
id_consumer:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 53bffc3900006400017e5db8
id_legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '9'
id_product:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 507f191e810c19729de860eas
language:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: en
legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Trustpilot
locale:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: en-US
mpn:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 7TX1641
product_gtin:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 01234567890
product_name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Metal Toy Car
product_sku:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ABC-1234
product_url:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ''
productimage_type:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ''
productimage_url:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ''
rating:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '5'
redirect_uri:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '''https://www.example.com'''
id_reference:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ABC-123-xyz
sate:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: ''
stars:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '5'
