bundle_name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Logic Compact + 2 pod + Pocket dynamic
bundle_sku:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Logic Compact + 2 pod + Pocket
country:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: IT
harmonization_status:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: VALID
id_bundle:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '2366'
id_legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '3'
legacy_system:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Magento
simple_product_id:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '938'
simple_product_name:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Logic Compact
simple_product_oprion_id:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '970'
simple_product_position:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: '1'
simple_product_sku:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: 20BD092250
sector_code:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: F5
brand:
  json_type: string
  td_type: varchar
  mandatory: true
  pydantic_type: StrictStr
  example: Ploom
